version: "3.7"

services:
  db:
    image: mysql
    platform: linux/amd64
    container_name: mysql-con
    env_file:
      - ./.env
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - data_mysql:/mysql
    networks:
      - app-tier
    # 명령어 실행 끝나도 안꺼짐
    tty: true

  backend:
    links:
      - db
    container_name: backend-con
    build:
      context: ./backend
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend:/backend/
    # restart: always 배포때만
    env_file:
      - ./.env
    depends_on:
      - db
    # command: 
    networks:
      - app-tier
    # 명령어 실행 끝나도 안꺼짐
    tty: true
  
  frontend-web:
    container_name: frontend-web-con
    build: ./frontend-web
    command: ["yarn", "start"]

    networks:
      - app-tier
    volumes:
      - ./frontend-web/:/frontend-web
      - build_folder:/frontend-web/build
      - ./frontend-web/node_modules/:/frontend-web/node_modules
    ports:
      - 3000:3000

  nginx:
    container_name: nginx-con
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    # 자동으로 6시간마다 nginx reload

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # 자동으로 12시간마다 재발급

networks:
  app-tier:
    external: true
  
volumes:
  data_mysql:
  build_folder: