version: "3"

services:
  backend:
    build: ./backend

    command: ash -c "python wait_for_mysql.py  && uvicorn main:app --host 0.0.0.0 --reload"
    #env_file:
    #  - ./settings/.env
    networks:
      - app-tier
    volumes:
      - ./backend/:/backend/
    ports:
      - 5000:5000

  frontendWeb:
    build: ./frontendWeb
    command: ["yarn", "start"]

    networks:
      - app-tier
    volumes:
      - ./frontendWeb/:/frontendWeb
      - build_folder:/frontendWeb/build
      - ./frontendWeb/node_modules/:/frontendWeb/node_modules
    ports:
      - 80:3000

  #frontendApp 부분(아직 작성 안함)
  
networks:
  app-tier:
    driver: bridge

# 컨테이너 내려도 데이터 유지되도록 함
volumes:
  media_volume: null
  build_folder: null